[tool.poetry]
name = "sperry"
version = "0.1.0"
description = "Parse, generate and manipulate KiCAD files"
authors = ["Günther Jena"]
license = "MIT"
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
